### ISSUE TITLE
Can not Install on Contao 4.4.7

### ISSUE THREAD

**Issue by captainKeller** [netzmacht/contao-cache-control#4]
Hi I can not install on Contao  4.4.7 i get the error 
`- contao/core 3.5.9 conflicts with contao/managed-edition[No version set (parsed as 1.0.0)].`

**Comment by dmolineus** [comment]
At the moment you simply can't. Contao 4 changes the way the cache is generated. So this extension does not work anymore.

Maybe Contao 4.5 will provide a solution to use this extension again. For further information you may have a look at https://github.com/contao/manager-bundle/issues/46

**Comment by dmolineus** [comment]
Since Contao 4.6 provides a powerful auto cache invalidation I won't migrate this package to Contao 4.
